
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DigiFactSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    mx.gob.sat.cartaporte.ObjectFactory.class,
    mx.gob.sat.detallista.ObjectFactory.class,
    mx.gob.sat.ine.ObjectFactory.class,
    mx.gob.sat.aerolineas.ObjectFactory.class,
    mx.gob.sat.cartaporte20.ObjectFactory.class,
    mx.gob.sat.cartaporte30.ObjectFactory.class,
    mx.gob.sat.cartaporte31.ObjectFactory.class,
    mx.gob.sat.cfd._3.ObjectFactory.class,
    mx.gob.sat.divisas.ObjectFactory.class,
    mx.gob.sat.donat.ObjectFactory.class,
    mx.gob.sat.gastoshidrocarburos10.ObjectFactory.class,
    mx.gob.sat.iedu.ObjectFactory.class,
    mx.gob.sat.leyendasfiscales.ObjectFactory.class,
    mx.gob.sat.nomina12.ObjectFactory.class,
    mx.gob.sat.notariospublicos.ObjectFactory.class,
    mx.gob.sat.servicioparcialconstruccion.ObjectFactory.class,
    mx.gob.sat.terceros.ObjectFactory.class,
    mx.gob.sat.valesdedespensa.ObjectFactory.class,
    mx.gob.sat.vehiculousado.ObjectFactory.class,
    mx.gob.sat.ventavehiculos.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface DigiFactSoap {


    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIV33", action = "http://tempuri.org/GeneraCFDIV33")
    @WebResult(name = "GeneraCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33")
    @ResponseWrapper(localName = "GeneraCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33Response")
    public CFDIResponse generaCFDIV33(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest cfdiRequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIVPase", action = "http://tempuri.org/GeneraCFDIVPase")
    @WebResult(name = "GeneraCFDIVPaseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIVPase", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIVPase")
    @ResponseWrapper(localName = "GeneraCFDIVPaseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIVPaseResponse")
    public CFDIResponse generaCFDIVPase(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest cfdiRequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIVPaseMasivo", action = "http://tempuri.org/GeneraCFDIVPaseMasivo")
    @WebResult(name = "GeneraCFDIVPaseMasivoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIVPaseMasivo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIVPaseMasivo")
    @ResponseWrapper(localName = "GeneraCFDIVPaseMasivoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIVPaseMasivoResponse")
    public CFDIResponse generaCFDIVPaseMasivo(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest cfdiRequest);

    /**
     * 
     * @param cfdiRequest40
     * @return
     *     returns org.tempuri.CFDIResponse40
     */
    @WebMethod(operationName = "GeneraCFDIV40", action = "http://tempuri.org/GeneraCFDIV40")
    @WebResult(name = "GeneraCFDIV40Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40")
    @ResponseWrapper(localName = "GeneraCFDIV40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40Response")
    public CFDIResponse40 generaCFDIV40(
        @WebParam(name = "CFDIRequest40", targetNamespace = "http://tempuri.org/")
        CFDIRequest40 cfdiRequest40);

    /**
     * 
     * @param cfdiRequest40
     * @return
     *     returns org.tempuri.CFDIResponse40Allianz
     */
    @WebMethod(operationName = "GeneraCFDIV40Allianz", action = "http://tempuri.org/GeneraCFDIV40Allianz")
    @WebResult(name = "GeneraCFDIV40AllianzResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV40Allianz", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40Allianz")
    @ResponseWrapper(localName = "GeneraCFDIV40AllianzResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40AllianzResponse")
    public CFDIResponse40Allianz generaCFDIV40Allianz(
        @WebParam(name = "CFDIRequest40", targetNamespace = "http://tempuri.org/")
        CFDIRequest40Allianz cfdiRequest40);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse40ComplementoDePagos
     */
    @WebMethod(operationName = "GeneraCFDIV40CPagos", action = "http://tempuri.org/GeneraCFDIV40CPagos")
    @WebResult(name = "GeneraCFDIV40CPagosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV40CPagos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40CPagos")
    @ResponseWrapper(localName = "GeneraCFDIV40CPagosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40CPagosResponse")
    public CFDIResponse40ComplementoDePagos generaCFDIV40CPagos(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest40ComplementoDePago cfdiRequest);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.CFDIComercioExteriorResponse40
     */
    @WebMethod(operationName = "GeneraCFDIComerioExterior11V40", action = "http://tempuri.org/GeneraCFDIComerioExterior11V40")
    @WebResult(name = "GeneraCFDIComerioExterior11V40Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIComerioExterior11V40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11V40")
    @ResponseWrapper(localName = "GeneraCFDIComerioExterior11V40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11V40Response")
    public CFDIComercioExteriorResponse40 generaCFDIComerioExterior11V40(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        CFDIComercioExteriorRequest33 comerciorequest);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.CFDIComercioExterior20Response
     */
    @WebMethod(operationName = "GeneraCFDIComerioExterior20V40", action = "http://tempuri.org/GeneraCFDIComerioExterior20V40")
    @WebResult(name = "GeneraCFDIComerioExterior20V40Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIComerioExterior20V40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior20V40")
    @ResponseWrapper(localName = "GeneraCFDIComerioExterior20V40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior20V40Response")
    public CFDIComercioExterior20Response generaCFDIComerioExterior20V40(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        CFDIComercioExterior20Request comerciorequest);

    /**
     * 
     * @param retencionesRequest
     * @return
     *     returns org.tempuri.RetencionesResponse
     */
    @WebMethod(operationName = "GeneraRetencion", action = "http://tempuri.org/GeneraRetencion")
    @WebResult(name = "GeneraRetencionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraRetencion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraRetencion")
    @ResponseWrapper(localName = "GeneraRetencionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraRetencionResponse")
    public RetencionesResponse generaRetencion(
        @WebParam(name = "RetencionesRequest", targetNamespace = "http://tempuri.org/")
        RetencionesRequest retencionesRequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIV40SiVale", action = "http://tempuri.org/GeneraCFDIV40SiVale")
    @WebResult(name = "GeneraCFDIV40SiValeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV40SiVale", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40SiVale")
    @ResponseWrapper(localName = "GeneraCFDIV40SiValeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40SiValeResponse")
    public CFDIResponse generaCFDIV40SiVale(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequestSiVale cfdiRequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponseHamilton
     */
    @WebMethod(operationName = "GeneraCFDIV33HamiltonBeach", action = "http://tempuri.org/GeneraCFDIV33HamiltonBeach")
    @WebResult(name = "GeneraCFDIV33HamiltonBeachResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33HamiltonBeach", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33HamiltonBeach")
    @ResponseWrapper(localName = "GeneraCFDIV33HamiltonBeachResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33HamiltonBeachResponse")
    public CFDIResponseHamilton generaCFDIV33HamiltonBeach(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequestHamilton cfdiRequest);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.CFDIComercioExteriorResponse33
     */
    @WebMethod(operationName = "GeneraCFDIComerioExteriorHamilton11V33", action = "http://tempuri.org/GeneraCFDIComerioExteriorHamilton11V33")
    @WebResult(name = "GeneraCFDIComerioExteriorHamilton11V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIComerioExteriorHamilton11V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExteriorHamilton11V33")
    @ResponseWrapper(localName = "GeneraCFDIComerioExteriorHamilton11V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExteriorHamilton11V33Response")
    public CFDIComercioExteriorResponse33 generaCFDIComerioExteriorHamilton11V33(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        CFDIComercioExteriorRequest33 comerciorequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse40ComplementoDePagos
     */
    @WebMethod(operationName = "GeneraCFDIV40CPagosPase", action = "http://tempuri.org/GeneraCFDIV40CPagosPase")
    @WebResult(name = "GeneraCFDIV40CPagosPaseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV40CPagosPase", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40CPagosPase")
    @ResponseWrapper(localName = "GeneraCFDIV40CPagosPaseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV40CPagosPaseResponse")
    public CFDIResponse40ComplementoDePagos generaCFDIV40CPagosPase(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest40ComplementoDePago cfdiRequest);

    /**
     * 
     * @param pagosBPRequest
     * @return
     *     returns org.tempuri.PagosBPResponse
     */
    @WebMethod(operationName = "ObtenXMLRelacionados", action = "http://tempuri.org/ObtenXMLRelacionados")
    @WebResult(name = "ObtenXMLRelacionadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenXMLRelacionados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenXMLRelacionados")
    @ResponseWrapper(localName = "ObtenXMLRelacionadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenXMLRelacionadosResponse")
    public PagosBPResponse obtenXMLRelacionados(
        @WebParam(name = "pagosBPRequest", targetNamespace = "http://tempuri.org/")
        PagosBPRequest pagosBPRequest);

    /**
     * 
     * @param xmlrequest
     * @return
     *     returns org.tempuri.XMLCFDIResponse
     */
    @WebMethod(operationName = "ObtenXML33", action = "http://tempuri.org/ObtenXML33")
    @WebResult(name = "ObtenXML33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenXML33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenXML33")
    @ResponseWrapper(localName = "ObtenXML33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenXML33Response")
    public XMLCFDIResponse obtenXML33(
        @WebParam(name = "xmlrequest", targetNamespace = "http://tempuri.org/")
        XMLCFDIRequest xmlrequest);

    /**
     * 
     * @param cancelacionRetencionRequest
     * @return
     *     returns org.tempuri.CancelacionRetencionResponse
     */
    @WebMethod(operationName = "CancelaRetencion20", action = "http://tempuri.org/CancelaRetencion20")
    @WebResult(name = "CancelaRetencion20Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaRetencion20", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaRetencion20")
    @ResponseWrapper(localName = "CancelaRetencion20Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaRetencion20Response")
    public CancelacionRetencionResponse cancelaRetencion20(
        @WebParam(name = "CancelacionRetencionRequest", targetNamespace = "http://tempuri.org/")
        CancelacionRetencionRequest cancelacionRetencionRequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDINominaCancelacionResponse33
     */
    @WebMethod(operationName = "CancelaCFDINomina12V33", action = "http://tempuri.org/CancelaCFDINomina12V33")
    @WebResult(name = "CancelaCFDINomina12V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDINomina12V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINomina12V33")
    @ResponseWrapper(localName = "CancelaCFDINomina12V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINomina12V33Response")
    public CFDINominaCancelacionResponse33 cancelaCFDINomina12V33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDICancelacionNominaRequest33 cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDIv33CancelacionResponse
     */
    @WebMethod(operationName = "CancelaCFDIV33", action = "http://tempuri.org/CancelaCFDIV33")
    @WebResult(name = "CancelaCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33")
    @ResponseWrapper(localName = "CancelaCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33Response")
    public CFDIv33CancelacionResponse cancelaCFDIV33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDIv33CancelacionRequest cancelacionrequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.CFDINominaResponse33
     */
    @WebMethod(operationName = "GeneraCFDINomina12V40", action = "http://tempuri.org/GeneraCFDINomina12V40")
    @WebResult(name = "GeneraCFDINomina12V40Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDINomina12V40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12V40")
    @ResponseWrapper(localName = "GeneraCFDINomina12V40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12V40Response")
    public CFDINominaResponse33 generaCFDINomina12V40(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        CFDINominaRequest33 nominarequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaResponse33
     */
    @WebMethod(operationName = "TimbraCFDINominaPlus12V40", action = "http://tempuri.org/TimbraCFDINominaPlus12V40")
    @WebResult(name = "TimbraCFDINominaPlus12V40Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDINominaPlus12V40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12V40")
    @ResponseWrapper(localName = "TimbraCFDINominaPlus12V40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12V40Response")
    public TimbradoPlusNominaResponse33 timbraCFDINominaPlus12V40(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        TimbradoPlusNominaRequest33 nominarequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDITimbradoPlusReponse40ComplementoDePagos
     */
    @WebMethod(operationName = "GeneraCFDPlusV40ComplementoDePagos", action = "http://tempuri.org/GeneraCFDPlusV40ComplementoDePagos")
    @WebResult(name = "GeneraCFDPlusV40ComplementoDePagosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDPlusV40ComplementoDePagos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDPlusV40ComplementoDePagos")
    @ResponseWrapper(localName = "GeneraCFDPlusV40ComplementoDePagosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDPlusV40ComplementoDePagosResponse")
    public CFDITimbradoPlusReponse40ComplementoDePagos generaCFDPlusV40ComplementoDePagos(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDITimbradoPlusRequest40ComplementoDePagos cfdiRequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CancelacionV33ResponseConsulta
     */
    @WebMethod(operationName = "GetEstatusCFDI33", action = "http://tempuri.org/GetEstatusCFDI33")
    @WebResult(name = "GetEstatusCFDI33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEstatusCFDI33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEstatusCFDI33")
    @ResponseWrapper(localName = "GetEstatusCFDI33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEstatusCFDI33Response")
    public CancelacionV33ResponseConsulta getEstatusCFDI33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDIv33CancelacionRequestEstatus cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CancelacionV33ResponseConsulta
     */
    @WebMethod(operationName = "GetEstatusTFD33", action = "http://tempuri.org/GetEstatusTFD33")
    @WebResult(name = "GetEstatusTFD33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEstatusTFD33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEstatusTFD33")
    @ResponseWrapper(localName = "GetEstatusTFD33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEstatusTFD33Response")
    public CancelacionV33ResponseConsulta getEstatusTFD33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDIv33CancelacionRequestEstatus cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDIv33CancelacionResponse
     */
    @WebMethod(operationName = "CancelaCFDIV33SNValidacion", action = "http://tempuri.org/CancelaCFDIV33SNValidacion")
    @WebResult(name = "CancelaCFDIV33SNValidacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDIV33SNValidacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33SNValidacion")
    @ResponseWrapper(localName = "CancelaCFDIV33SNValidacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33SNValidacionResponse")
    public CFDIv33CancelacionResponse cancelaCFDIV33SNValidacion(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDIv33CancelacionRequest cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDIv33CancelacionResponseBP
     */
    @WebMethod(operationName = "CancelaCFDIV33BP", action = "http://tempuri.org/CancelaCFDIV33BP")
    @WebResult(name = "CancelaCFDIV33BPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDIV33BP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33BP")
    @ResponseWrapper(localName = "CancelaCFDIV33BPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33BPResponse")
    public CFDIv33CancelacionResponseBP cancelaCFDIV33BP(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDIv33CancelacionRequestBP cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDIv33CancelacionResponseBPSAP
     */
    @WebMethod(operationName = "CancelaCFDIV33BPSAP", action = "http://tempuri.org/CancelaCFDIV33BPSAP")
    @WebResult(name = "CancelaCFDIV33BPSAPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDIV33BPSAP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33BPSAP")
    @ResponseWrapper(localName = "CancelaCFDIV33BPSAPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDIV33BPSAPResponse")
    public CFDIv33CancelacionResponseBPSAP cancelaCFDIV33BPSAP(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDIv33CancelacionRequestBPSAP cancelacionrequest);

    /**
     * 
     * @param cfdiRequest40
     * @return
     *     returns org.tempuri.CFDITimbradoPlusReponse40
     */
    @WebMethod(operationName = "TimbraCFDIPlus40", action = "http://tempuri.org/TimbraCFDIPlus40")
    @WebResult(name = "TimbraCFDIPlus40Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIPlus40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIPlus40")
    @ResponseWrapper(localName = "TimbraCFDIPlus40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIPlus40Response")
    public CFDITimbradoPlusReponse40 timbraCFDIPlus40(
        @WebParam(name = "CFDIRequest40", targetNamespace = "http://tempuri.org/")
        CFDITimbradoPlusRequest40 cfdiRequest40);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.Timbradov33CancelacionResponse
     */
    @WebMethod(operationName = "CancelaTFDV33", action = "http://tempuri.org/CancelaTFDV33")
    @WebResult(name = "CancelaTFDV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaTFDV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaTFDV33")
    @ResponseWrapper(localName = "CancelaTFDV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaTFDV33Response")
    public Timbradov33CancelacionResponse cancelaTFDV33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        Timbradov33CancelacionRequest cancelacionrequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaCancelacionResponse33
     */
    @WebMethod(operationName = "CancelaCFDINominaPlus12V33", action = "http://tempuri.org/CancelaCFDINominaPlus12V33")
    @WebResult(name = "CancelaCFDINominaPlus12V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDINominaPlus12V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINominaPlus12V33")
    @ResponseWrapper(localName = "CancelaCFDINominaPlus12V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINominaPlus12V33Response")
    public TimbradoPlusNominaCancelacionResponse33 cancelaCFDINominaPlus12V33(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        TibradoPlusNominaCancelacioRequest33 cancelacionrequest);

    /**
     * 
     * @param cancelacionRequest
     * @return
     *     returns org.tempuri.CancelacionV33ResponseConsulta
     */
    @WebMethod(operationName = "ConsultaEstatusFacturaV33", action = "http://tempuri.org/ConsultaEstatusFacturaV33")
    @WebResult(name = "ConsultaEstatusFacturaV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaEstatusFacturaV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaEstatusFacturaV33")
    @ResponseWrapper(localName = "ConsultaEstatusFacturaV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaEstatusFacturaV33Response")
    public CancelacionV33ResponseConsulta consultaEstatusFacturaV33(
        @WebParam(name = "cancelacionRequest", targetNamespace = "http://tempuri.org/")
        CancelacionV33RequestConsulta cancelacionRequest);

    /**
     * 
     * @param validacionFacturaRequest
     * @return
     *     returns org.tempuri.ValidacionFacturaResponse
     */
    @WebMethod(operationName = "ValidaFacturaExterno", action = "http://tempuri.org/ValidaFacturaExterno")
    @WebResult(name = "ValidaFacturaExternoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidaFacturaExterno", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidaFacturaExterno")
    @ResponseWrapper(localName = "ValidaFacturaExternoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidaFacturaExternoResponse")
    public ValidacionFacturaResponse validaFacturaExterno(
        @WebParam(name = "ValidacionFacturaRequest", targetNamespace = "http://tempuri.org/")
        ValidacionFacturaRequest validacionFacturaRequest);

    /**
     * 
     * @param requestOtroPac
     * @return
     *     returns org.tempuri.CancelacionResponseOtroPac
     */
    @WebMethod(operationName = "SubeArchivoOtroPac", action = "http://tempuri.org/SubeArchivoOtroPac")
    @WebResult(name = "SubeArchivoOtroPacResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SubeArchivoOtroPac", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SubeArchivoOtroPac")
    @ResponseWrapper(localName = "SubeArchivoOtroPacResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SubeArchivoOtroPacResponse")
    public CancelacionResponseOtroPac subeArchivoOtroPac(
        @WebParam(name = "requestOtroPac", targetNamespace = "http://tempuri.org/")
        CancelacionRequestOtroPac requestOtroPac);

    /**
     * 
     * @param pagosBPRequest
     * @return
     *     returns org.tempuri.PagosBPResponse
     */
    @WebMethod(operationName = "ObtenXMLPagosGenerados", action = "http://tempuri.org/ObtenXMLPagosGenerados")
    @WebResult(name = "ObtenXMLPagosGeneradosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenXMLPagosGenerados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenXMLPagosGenerados")
    @ResponseWrapper(localName = "ObtenXMLPagosGeneradosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenXMLPagosGeneradosResponse")
    public PagosBPResponse obtenXMLPagosGenerados(
        @WebParam(name = "pagosBPRequest", targetNamespace = "http://tempuri.org/")
        PagosBPRequest pagosBPRequest);

    /**
     * 
     * @param qrRequest
     * @return
     *     returns org.tempuri.QRCodeResponse
     */
    @WebMethod(operationName = "GenerBytesQRCode", action = "http://tempuri.org/GenerBytesQRCode")
    @WebResult(name = "GenerBytesQRCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerBytesQRCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerBytesQRCode")
    @ResponseWrapper(localName = "GenerBytesQRCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerBytesQRCodeResponse")
    public QRCodeResponse generBytesQRCode(
        @WebParam(name = "QRRequest", targetNamespace = "http://tempuri.org/")
        QRCodeRequest qrRequest);

    /**
     * 
     * @param requets
     * @return
     *     returns org.tempuri.ResponseAsignacion
     */
    @WebMethod(operationName = "AsignaFolios", action = "http://tempuri.org/AsignaFolios")
    @WebResult(name = "AsignaFoliosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AsignaFolios", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AsignaFolios")
    @ResponseWrapper(localName = "AsignaFoliosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AsignaFoliosResponse")
    public ResponseAsignacion asignaFolios(
        @WebParam(name = "requets", targetNamespace = "http://tempuri.org/")
        RequestAsignacion requets);

    /**
     * 
     * @param requets
     * @return
     *     returns org.tempuri.ResponseAsignacion
     */
    @WebMethod(operationName = "RetiraFolios", action = "http://tempuri.org/RetiraFolios")
    @WebResult(name = "RetiraFoliosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetiraFolios", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RetiraFolios")
    @ResponseWrapper(localName = "RetiraFoliosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RetiraFoliosResponse")
    public ResponseAsignacion retiraFolios(
        @WebParam(name = "requets", targetNamespace = "http://tempuri.org/")
        RequestAsignacion requets);

    /**
     * 
     * @param facturaGRequest
     * @return
     *     returns org.tempuri.FacturaGlobalResponse
     */
    @WebMethod(operationName = "GeneraListaTicketsCrepes", action = "http://tempuri.org/GeneraListaTicketsCrepes")
    @WebResult(name = "GeneraListaTicketsCrepesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraListaTicketsCrepes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraListaTicketsCrepes")
    @ResponseWrapper(localName = "GeneraListaTicketsCrepesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraListaTicketsCrepesResponse")
    public FacturaGlobalResponse generaListaTicketsCrepes(
        @WebParam(name = "facturaGRequest", targetNamespace = "http://tempuri.org/")
        FacturaGlobalRequest facturaGRequest);

    /**
     * 
     * @param facturaGRequest
     * @param facturaGResponse
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ActualizaEstatusTicketsCrepes", action = "http://tempuri.org/ActualizaEstatusTicketsCrepes")
    @WebResult(name = "ActualizaEstatusTicketsCrepesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizaEstatusTicketsCrepes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActualizaEstatusTicketsCrepes")
    @ResponseWrapper(localName = "ActualizaEstatusTicketsCrepesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActualizaEstatusTicketsCrepesResponse")
    public boolean actualizaEstatusTicketsCrepes(
        @WebParam(name = "facturaGRequest", targetNamespace = "http://tempuri.org/")
        FacturaGlobalRequest facturaGRequest,
        @WebParam(name = "facturaGResponse", targetNamespace = "http://tempuri.org/")
        FacturaGlobalResponse facturaGResponse);

    /**
     * 
     * @param certificadosRequest
     * @return
     *     returns org.tempuri.CertificadosResponse
     */
    @WebMethod(operationName = "ObtenCertificados", action = "http://tempuri.org/ObtenCertificados")
    @WebResult(name = "ObtenCertificadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenCertificados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenCertificados")
    @ResponseWrapper(localName = "ObtenCertificadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenCertificadosResponse")
    public CertificadosResponse obtenCertificados(
        @WebParam(name = "certificadosRequest", targetNamespace = "http://tempuri.org/")
        CertificadosRequest certificadosRequest);

    /**
     * 
     * @param decimalesRequest
     * @return
     *     returns org.tempuri.DecimalesResponse
     */
    @WebMethod(operationName = "CambiaDecimalesV33", action = "http://tempuri.org/CambiaDecimalesV33")
    @WebResult(name = "CambiaDecimalesV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CambiaDecimalesV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CambiaDecimalesV33")
    @ResponseWrapper(localName = "CambiaDecimalesV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CambiaDecimalesV33Response")
    public DecimalesResponse cambiaDecimalesV33(
        @WebParam(name = "decimalesRequest", targetNamespace = "http://tempuri.org/")
        DecimalesRequest decimalesRequest);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.TicketGandhiResponse
     */
    @WebMethod(operationName = "IntroduceTicketGandhi", action = "http://tempuri.org/IntroduceTicketGandhi")
    @WebResult(name = "IntroduceTicketGandhiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IntroduceTicketGandhi", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceTicketGandhi")
    @ResponseWrapper(localName = "IntroduceTicketGandhiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceTicketGandhiResponse")
    public TicketGandhiResponse introduceTicketGandhi(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
        TicketGandhiRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.CPagoBPResponse
     */
    @WebMethod(operationName = "ObtenPagoArchivoBP", action = "http://tempuri.org/ObtenPagoArchivoBP")
    @WebResult(name = "ObtenPagoArchivoBPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenPagoArchivoBP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenPagoArchivoBP")
    @ResponseWrapper(localName = "ObtenPagoArchivoBPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenPagoArchivoBPResponse")
    public CPagoBPResponse obtenPagoArchivoBP(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
        CPagoBPRequest request);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnvioCorreosBPDownstream", action = "http://tempuri.org/EnvioCorreosBPDownstream")
    @WebResult(name = "EnvioCorreosBPDownstreamResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnvioCorreosBPDownstream", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnvioCorreosBPDownstream")
    @ResponseWrapper(localName = "EnvioCorreosBPDownstreamResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnvioCorreosBPDownstreamResponse")
    public String envioCorreosBPDownstream(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena);

    /**
     * 
     * @param sapRequest
     * @return
     *     returns org.tempuri.SAPResponse
     */
    @WebMethod(operationName = "GuardaInfoSAP", action = "http://tempuri.org/GuardaInfoSAP")
    @WebResult(name = "GuardaInfoSAPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GuardaInfoSAP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GuardaInfoSAP")
    @ResponseWrapper(localName = "GuardaInfoSAPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GuardaInfoSAPResponse")
    public SAPResponse guardaInfoSAP(
        @WebParam(name = "SAPRequest", targetNamespace = "http://tempuri.org/")
        SAPRequest sapRequest);

    /**
     * 
     * @param pdfrequest
     * @return
     *     returns org.tempuri.PDFNominaResponse
     */
    @WebMethod(operationName = "GeneraPDFNomina12", action = "http://tempuri.org/GeneraPDFNomina12")
    @WebResult(name = "GeneraPDFNomina12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFNomina12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFNomina12")
    @ResponseWrapper(localName = "GeneraPDFNomina12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFNomina12Response")
    public PDFNominaResponse generaPDFNomina12(
        @WebParam(name = "pdfrequest", targetNamespace = "http://tempuri.org/")
        PDFNominaRquest pdfrequest);

    /**
     * 
     * @param pdfrequest
     * @return
     *     returns org.tempuri.PDFCFDIResponse
     */
    @WebMethod(operationName = "GeneraPDFCFDIV33", action = "http://tempuri.org/GeneraPDFCFDIV33")
    @WebResult(name = "GeneraPDFCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFCFDIV33")
    @ResponseWrapper(localName = "GeneraPDFCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFCFDIV33Response")
    public PDFCFDIResponse generaPDFCFDIV33(
        @WebParam(name = "pdfrequest", targetNamespace = "http://tempuri.org/")
        PDFCFDIRquest pdfrequest);

    /**
     * 
     * @param pdfcfdiRequestComplemento
     * @return
     *     returns org.tempuri.PDFCFDIResponse
     */
    @WebMethod(operationName = "GeneraPDFComplemento", action = "http://tempuri.org/GeneraPDFComplemento")
    @WebResult(name = "GeneraPDFComplementoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFComplemento", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFComplemento")
    @ResponseWrapper(localName = "GeneraPDFComplementoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFComplementoResponse")
    public PDFCFDIResponse generaPDFComplemento(
        @WebParam(name = "PDFCFDIRequestComplemento", targetNamespace = "http://tempuri.org/")
        PDFCFDIRequestComplemento pdfcfdiRequestComplemento);

    /**
     * 
     * @param pdfrequest
     * @return
     *     returns org.tempuri.PDFCFDIResponseSumma
     */
    @WebMethod(operationName = "GeneraPDFCFDIV33Summa", action = "http://tempuri.org/GeneraPDFCFDIV33Summa")
    @WebResult(name = "GeneraPDFCFDIV33SummaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFCFDIV33Summa", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFCFDIV33Summa")
    @ResponseWrapper(localName = "GeneraPDFCFDIV33SummaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFCFDIV33SummaResponse")
    public PDFCFDIResponseSumma generaPDFCFDIV33Summa(
        @WebParam(name = "pdfrequest", targetNamespace = "http://tempuri.org/")
        PDFCFDIRquest pdfrequest);

    /**
     * 
     * @param pdfrequest
     * @return
     *     returns org.tempuri.PDFCFDIResponseOM
     */
    @WebMethod(operationName = "GeneraPDFCFDIV33OfficeMax", action = "http://tempuri.org/GeneraPDFCFDIV33OfficeMax")
    @WebResult(name = "GeneraPDFCFDIV33OfficeMaxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFCFDIV33OfficeMax", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFCFDIV33OfficeMax")
    @ResponseWrapper(localName = "GeneraPDFCFDIV33OfficeMaxResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFCFDIV33OfficeMaxResponse")
    public PDFCFDIResponseOM generaPDFCFDIV33OfficeMax(
        @WebParam(name = "pdfrequest", targetNamespace = "http://tempuri.org/")
        PDFCFDIRquestOM pdfrequest);

    /**
     * 
     * @param timbraRequest
     * @return
     *     returns org.tempuri.TimbraCFDI40Response
     */
    @WebMethod(operationName = "TimbraCFDIV40", action = "http://tempuri.org/TimbraCFDIV40")
    @WebResult(name = "TimbraCFDIV40Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIV40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV40")
    @ResponseWrapper(localName = "TimbraCFDIV40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV40Response")
    public TimbraCFDI40Response timbraCFDIV40(
        @WebParam(name = "timbraRequest", targetNamespace = "http://tempuri.org/")
        TimbraCFDI40Request timbraRequest);

    /**
     * 
     * @param timbraRequest
     * @return
     *     returns org.tempuri.TimbraCFDI40Response
     */
    @WebMethod(operationName = "TimbraCFDIV40B64", action = "http://tempuri.org/TimbraCFDIV40B64")
    @WebResult(name = "TimbraCFDIV40B64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIV40B64", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV40B64")
    @ResponseWrapper(localName = "TimbraCFDIV40B64Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV40B64Response")
    public TimbraCFDI40Response timbraCFDIV40B64(
        @WebParam(name = "timbraRequest", targetNamespace = "http://tempuri.org/")
        TimbraCFDI40Request timbraRequest);

    /**
     * 
     * @param timbraRequest
     * @return
     *     returns org.tempuri.TimbraCFDI40Response
     */
    @WebMethod(operationName = "TimbraCFDIV3340B64Allianz", action = "http://tempuri.org/TimbraCFDIV3340B64Allianz")
    @WebResult(name = "TimbraCFDIV3340B64AllianzResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIV3340B64Allianz", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV3340B64Allianz")
    @ResponseWrapper(localName = "TimbraCFDIV3340B64AllianzResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV3340B64AllianzResponse")
    public TimbraCFDI40Response timbraCFDIV3340B64Allianz(
        @WebParam(name = "timbraRequest", targetNamespace = "http://tempuri.org/")
        TimbraCFDI40RequestAllianz timbraRequest);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.TicketResponse
     */
    @WebMethod(operationName = "IntroduceDatosTicketV33", action = "http://tempuri.org/IntroduceDatosTicketV33")
    @WebResult(name = "IntroduceDatosTicketV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IntroduceDatosTicketV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTicketV33")
    @ResponseWrapper(localName = "IntroduceDatosTicketV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTicketV33Response")
    public TicketResponse introduceDatosTicketV33(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
        TicketRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.TicketResponse40
     */
    @WebMethod(operationName = "IntroduceDatosTicketV40", action = "http://tempuri.org/IntroduceDatosTicketV40")
    @WebResult(name = "IntroduceDatosTicketV40Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IntroduceDatosTicketV40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTicketV40")
    @ResponseWrapper(localName = "IntroduceDatosTicketV40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTicketV40Response")
    public TicketResponse40 introduceDatosTicketV40(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
        TicketRequest40 request);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.TicketResponse40Lanceta
     */
    @WebMethod(operationName = "IntroduceDatosTicketV40Lanceta", action = "http://tempuri.org/IntroduceDatosTicketV40Lanceta")
    @WebResult(name = "IntroduceDatosTicketV40LancetaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IntroduceDatosTicketV40Lanceta", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTicketV40Lanceta")
    @ResponseWrapper(localName = "IntroduceDatosTicketV40LancetaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTicketV40LancetaResponse")
    public TicketResponse40Lanceta introduceDatosTicketV40Lanceta(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
        TicketRequest40Lanceta request);

    /**
     * 
     * @param pdfrequest
     * @return
     *     returns org.tempuri.PDFTicketResponse
     */
    @WebMethod(operationName = "GeneraPDFTickets", action = "http://tempuri.org/GeneraPDFTickets")
    @WebResult(name = "GeneraPDFTicketsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPDFTickets", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFTickets")
    @ResponseWrapper(localName = "GeneraPDFTicketsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPDFTicketsResponse")
    public PDFTicketResponse generaPDFTickets(
        @WebParam(name = "pdfrequest", targetNamespace = "http://tempuri.org/")
        PDFTicketRquest pdfrequest);

    /**
     * 
     * @param cliente
     * @return
     *     returns org.tempuri.ClienteResponse
     */
    @WebMethod(operationName = "InsertaCliente", action = "http://tempuri.org/InsertaCliente")
    @WebResult(name = "InsertaClienteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertaCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertaCliente")
    @ResponseWrapper(localName = "InsertaClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertaClienteResponse")
    public ClienteResponse insertaCliente(
        @WebParam(name = "Cliente", targetNamespace = "http://tempuri.org/")
        Cliente cliente);

    /**
     * 
     * @param cliente
     * @return
     *     returns org.tempuri.ClienteResponse
     */
    @WebMethod(operationName = "ActualizaCliente", action = "http://tempuri.org/ActualizaCliente")
    @WebResult(name = "ActualizaClienteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizaCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActualizaCliente")
    @ResponseWrapper(localName = "ActualizaClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActualizaClienteResponse")
    public ClienteResponse actualizaCliente(
        @WebParam(name = "Cliente", targetNamespace = "http://tempuri.org/")
        ClienteActualiza cliente);

    /**
     * 
     * @param verificaDuplicidadRequest
     * @return
     *     returns org.tempuri.VerificaDuplicidadResponse2
     */
    @WebMethod(operationName = "VerificaDuplicidad", action = "http://tempuri.org/VerificaDuplicidad")
    @WebResult(name = "VerificaDuplicidadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VerificaDuplicidad", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerificaDuplicidad")
    @ResponseWrapper(localName = "VerificaDuplicidadResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerificaDuplicidadResponse")
    public VerificaDuplicidadResponse2 verificaDuplicidad(
        @WebParam(name = "verificaDuplicidadRequest", targetNamespace = "http://tempuri.org/")
        VerificaDuplicidadRequest verificaDuplicidadRequest);

    /**
     * 
     * @param logoRequest
     * @return
     *     returns org.tempuri.LogoResponse
     */
    @WebMethod(operationName = "CargaLogo", action = "http://tempuri.org/CargaLogo")
    @WebResult(name = "CargaLogoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargaLogo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaLogo")
    @ResponseWrapper(localName = "CargaLogoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaLogoResponse")
    public LogoResponse cargaLogo(
        @WebParam(name = "logoRequest", targetNamespace = "http://tempuri.org/")
        LogoRequest logoRequest);

    /**
     * 
     * @param certificate
     * @return
     *     returns org.tempuri.DataResponseCreate
     */
    @WebMethod(operationName = "CargaCertificado", action = "http://tempuri.org/CargaCertificado")
    @WebResult(name = "CargaCertificadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargaCertificado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaCertificado")
    @ResponseWrapper(localName = "CargaCertificadoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaCertificadoResponse")
    public DataResponseCreate cargaCertificado(
        @WebParam(name = "Certificate", targetNamespace = "http://tempuri.org/")
        CertificateRequest certificate);

    /**
     * 
     * @param fielRequest
     * @return
     *     returns org.tempuri.DataResponseFielB64
     */
    @WebMethod(operationName = "FirmaContrato", action = "http://tempuri.org/FirmaContrato")
    @WebResult(name = "FirmaContratoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FirmaContrato", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FirmaContrato")
    @ResponseWrapper(localName = "FirmaContratoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FirmaContratoResponse")
    public DataResponseFielB64 firmaContrato(
        @WebParam(name = "FielRequest", targetNamespace = "http://tempuri.org/")
        FielRequest fielRequest);

    /**
     * 
     * @param uploadSerie
     * @return
     *     returns org.tempuri.DataResponseCreate
     */
    @WebMethod(operationName = "CargaSerie", action = "http://tempuri.org/CargaSerie")
    @WebResult(name = "CargaSerieResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargaSerie", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaSerie")
    @ResponseWrapper(localName = "CargaSerieResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaSerieResponse")
    public DataResponseCreate cargaSerie(
        @WebParam(name = "uploadSerie", targetNamespace = "http://tempuri.org/")
        UploadSerieRequest uploadSerie);

    /**
     * 
     * @param envioSiValeRequest
     * @return
     *     returns org.tempuri.EnvioSiValeResponse
     */
    @WebMethod(operationName = "EnviaCorreoSivale", action = "http://tempuri.org/EnviaCorreoSivale")
    @WebResult(name = "EnviaCorreoSivaleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnviaCorreoSivale", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviaCorreoSivale")
    @ResponseWrapper(localName = "EnviaCorreoSivaleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviaCorreoSivaleResponse")
    public EnvioSiValeResponse enviaCorreoSivale(
        @WebParam(name = "EnvioSiValeRequest", targetNamespace = "http://tempuri.org/")
        EnvioSiValeRequest envioSiValeRequest);

    /**
     * 
     * @param validaRequest
     * @return
     *     returns org.tempuri.ValidaCFDI33Response
     */
    @WebMethod(operationName = "ValidaCFDIV33", action = "http://tempuri.org/ValidaCFDIV33")
    @WebResult(name = "ValidaCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidaCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidaCFDIV33")
    @ResponseWrapper(localName = "ValidaCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidaCFDIV33Response")
    public ValidaCFDI33Response validaCFDIV33(
        @WebParam(name = "validaRequest", targetNamespace = "http://tempuri.org/")
        ValidaCFDI33Request validaRequest);

    /**
     * 
     * @param consulta
     * @return
     *     returns org.tempuri.ConsultaReportesResponse
     */
    @WebMethod(operationName = "ConsultaBDReportes", action = "http://tempuri.org/ConsultaBDReportes")
    @WebResult(name = "ConsultaBDReportesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaBDReportes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaBDReportes")
    @ResponseWrapper(localName = "ConsultaBDReportesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaBDReportesResponse")
    public ConsultaReportesResponse consultaBDReportes(
        @WebParam(name = "consulta", targetNamespace = "http://tempuri.org/")
        ConsultaReportesRequest consulta);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.ReporteResponse
     */
    @WebMethod(operationName = "GeneraReporteTimbradoJson33", action = "http://tempuri.org/GeneraReporteTimbradoJson33")
    @WebResult(name = "GeneraReporteTimbradoJson33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraReporteTimbradoJson33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraReporteTimbradoJson33")
    @ResponseWrapper(localName = "GeneraReporteTimbradoJson33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraReporteTimbradoJson33Response")
    public ReporteResponse generaReporteTimbradoJson33(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        ReporteRequest request);

    /**
     * 
     * @return
     *     returns org.tempuri.ConexionResponse
     */
    @WebMethod(operationName = "ConsultaConexionBD", action = "http://tempuri.org/ConsultaConexionBD")
    @WebResult(name = "ConsultaConexionBDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaConexionBD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaConexionBD")
    @ResponseWrapper(localName = "ConsultaConexionBDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaConexionBDResponse")
    public ConexionResponse consultaConexionBD();

    /**
     * 
     * @param facturasPendientesRequest
     * @return
     *     returns org.tempuri.FacturasPendientesResponse
     */
    @WebMethod(operationName = "ObtenFacturasPendientesAceptacion", action = "http://tempuri.org/ObtenFacturasPendientesAceptacion")
    @WebResult(name = "ObtenFacturasPendientesAceptacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObtenFacturasPendientesAceptacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenFacturasPendientesAceptacion")
    @ResponseWrapper(localName = "ObtenFacturasPendientesAceptacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtenFacturasPendientesAceptacionResponse")
    public FacturasPendientesResponse obtenFacturasPendientesAceptacion(
        @WebParam(name = "FacturasPendientesRequest", targetNamespace = "http://tempuri.org/")
        FacturasPendientesRequest facturasPendientesRequest);

    /**
     * 
     * @param autorizaCancelacionRequest
     * @return
     *     returns org.tempuri.AutorizaCancelacionResponse
     */
    @WebMethod(operationName = "AutorizaFacturaCancelacion", action = "http://tempuri.org/AutorizaFacturaCancelacion")
    @WebResult(name = "AutorizaFacturaCancelacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AutorizaFacturaCancelacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AutorizaFacturaCancelacion")
    @ResponseWrapper(localName = "AutorizaFacturaCancelacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AutorizaFacturaCancelacionResponse")
    public AutorizaCancelacionResponse autorizaFacturaCancelacion(
        @WebParam(name = "AutorizaCancelacionRequest", targetNamespace = "http://tempuri.org/")
        AutorizaCancelacionRequest autorizaCancelacionRequest);

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.TransaccionResponse
     */
    @WebMethod(operationName = "IntroduceDatosTransaccionINAH", action = "http://tempuri.org/IntroduceDatosTransaccionINAH")
    @WebResult(name = "IntroduceDatosTransaccionINAHResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IntroduceDatosTransaccionINAH", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTransaccionINAH")
    @ResponseWrapper(localName = "IntroduceDatosTransaccionINAHResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IntroduceDatosTransaccionINAHResponse")
    public TransaccionResponse introduceDatosTransaccionINAH(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
        TransaccionRequest request);

    /**
     * 
     * @param cancelacionTransaccionRequest
     * @return
     *     returns org.tempuri.CancelacionTransaccionResponse
     */
    @WebMethod(operationName = "CancelaTransaccionINAH", action = "http://tempuri.org/CancelaTransaccionINAH")
    @WebResult(name = "CancelaTransaccionINAHResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaTransaccionINAH", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaTransaccionINAH")
    @ResponseWrapper(localName = "CancelaTransaccionINAHResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaTransaccionINAHResponse")
    public CancelacionTransaccionResponse cancelaTransaccionINAH(
        @WebParam(name = "CancelacionTransaccionRequest", targetNamespace = "http://tempuri.org/")
        CancelacionTransaccionRequest cancelacionTransaccionRequest);

    /**
     * 
     * @param catalogoDeCuentas
     * @param balanzaComprobacion
     * @param usuario
     * @param contrasena
     * @return
     *     returns org.tempuri.CatalogoBalanzaResponse
     */
    @WebMethod(operationName = "GeneraCatalogoConBalanza", action = "http://tempuri.org/GeneraCatalogoConBalanza")
    @WebResult(name = "GeneraCatalogoConBalanzaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCatalogoConBalanza", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCatalogoConBalanza")
    @ResponseWrapper(localName = "GeneraCatalogoConBalanzaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCatalogoConBalanzaResponse")
    public CatalogoBalanzaResponse generaCatalogoConBalanza(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "catalogoDeCuentas", targetNamespace = "http://tempuri.org/")
        CatalogoDeCuentas catalogoDeCuentas,
        @WebParam(name = "balanzaComprobacion", targetNamespace = "http://tempuri.org/")
        BalanzaComprobacion balanzaComprobacion);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param auxiliarCuentas
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraAuxiliarCuentas", action = "http://tempuri.org/GeneraAuxiliarCuentas")
    @WebResult(name = "GeneraAuxiliarCuentasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraAuxiliarCuentas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraAuxiliarCuentas")
    @ResponseWrapper(localName = "GeneraAuxiliarCuentasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraAuxiliarCuentasResponse")
    public String generaAuxiliarCuentas(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "auxiliarCuentas", targetNamespace = "http://tempuri.org/")
        AuxiliarCuentas auxiliarCuentas);

    /**
     * 
     * @param auxiliarFolios
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraAuxiliarFolios", action = "http://tempuri.org/GeneraAuxiliarFolios")
    @WebResult(name = "GeneraAuxiliarFoliosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraAuxiliarFolios", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraAuxiliarFolios")
    @ResponseWrapper(localName = "GeneraAuxiliarFoliosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraAuxiliarFoliosResponse")
    public String generaAuxiliarFolios(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "auxiliarFolios", targetNamespace = "http://tempuri.org/")
        AuxiliarFolios auxiliarFolios);

    /**
     * 
     * @param balanzaComprobacion
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraBalanzaComprobacion", action = "http://tempuri.org/GeneraBalanzaComprobacion")
    @WebResult(name = "GeneraBalanzaComprobacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraBalanzaComprobacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraBalanzaComprobacion")
    @ResponseWrapper(localName = "GeneraBalanzaComprobacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraBalanzaComprobacionResponse")
    public String generaBalanzaComprobacion(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "balanzaComprobacion", targetNamespace = "http://tempuri.org/")
        BalanzaComprobacion balanzaComprobacion);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param catalagoDeCuentas
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCatalogoCuentas", action = "http://tempuri.org/GeneraCatalogoCuentas")
    @WebResult(name = "GeneraCatalogoCuentasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCatalogoCuentas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCatalogoCuentas")
    @ResponseWrapper(localName = "GeneraCatalogoCuentasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCatalogoCuentasResponse")
    public String generaCatalogoCuentas(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "catalagoDeCuentas", targetNamespace = "http://tempuri.org/")
        CatalogoDeCuentas catalagoDeCuentas);

    /**
     * 
     * @param polizas
     * @param usuario
     * @param contrasena
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraPolizas", action = "http://tempuri.org/GeneraPolizas")
    @WebResult(name = "GeneraPolizasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPolizas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPolizas")
    @ResponseWrapper(localName = "GeneraPolizasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraPolizasResponse")
    public String generaPolizas(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "polizas", targetNamespace = "http://tempuri.org/")
        PolizasPeriodo polizas);

    /**
     * 
     * @param sorianaRequest
     * @return
     *     returns org.tempuri.SorianaResponse
     */
    @WebMethod(operationName = "EnviaXMLSoriana", action = "http://tempuri.org/EnviaXMLSoriana")
    @WebResult(name = "EnviaXMLSorianaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnviaXMLSoriana", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviaXMLSoriana")
    @ResponseWrapper(localName = "EnviaXMLSorianaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EnviaXMLSorianaResponse")
    public SorianaResponse enviaXMLSoriana(
        @WebParam(name = "SorianaRequest", targetNamespace = "http://tempuri.org/")
        SorianaRequest sorianaRequest);

    /**
     * 
     * @param usuario
     * @return
     *     returns org.tempuri.ResponseAsignacion
     */
    @WebMethod(operationName = "ConsultaFolios", action = "http://tempuri.org/ConsultaFolios")
    @WebResult(name = "ConsultaFoliosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaFolios", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaFolios")
    @ResponseWrapper(localName = "ConsultaFoliosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaFoliosResponse")
    public ResponseAsignacion consultaFolios(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario);

    /**
     * 
     * @param requestBellota
     * @return
     *     returns org.tempuri.ReporteResponseBellota
     */
    @WebMethod(operationName = "GeneraReporteBellota", action = "http://tempuri.org/GeneraReporteBellota")
    @WebResult(name = "GeneraReporteBellotaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraReporteBellota", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraReporteBellota")
    @ResponseWrapper(localName = "GeneraReporteBellotaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraReporteBellotaResponse")
    public ReporteResponseBellota generaReporteBellota(
        @WebParam(name = "RequestBellota", targetNamespace = "http://tempuri.org/")
        ReporteRequestBellota requestBellota);

    /**
     * 
     * @param paseRequest
     * @return
     *     returns org.tempuri.PASEResponse
     */
    @WebMethod(operationName = "AlmacenaXMLPase", action = "http://tempuri.org/AlmacenaXMLPase")
    @WebResult(name = "AlmacenaXMLPaseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AlmacenaXMLPase", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AlmacenaXMLPase")
    @ResponseWrapper(localName = "AlmacenaXMLPaseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AlmacenaXMLPaseResponse")
    public PASEResponse almacenaXMLPase(
        @WebParam(name = "PASERequest", targetNamespace = "http://tempuri.org/")
        PASERequest paseRequest);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.CFDIComercioExteriorResponse33
     */
    @WebMethod(operationName = "GeneraCFDIComerioExterior11V33", action = "http://tempuri.org/GeneraCFDIComerioExterior11V33")
    @WebResult(name = "GeneraCFDIComerioExterior11V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIComerioExterior11V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11V33")
    @ResponseWrapper(localName = "GeneraCFDIComerioExterior11V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11V33Response")
    public CFDIComercioExteriorResponse33 generaCFDIComerioExterior11V33(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        CFDIComercioExteriorRequest33 comerciorequest);

    /**
     * 
     * @param cambiorequest
     * @return
     *     returns org.tempuri.CambiaEstatus33Response
     */
    @WebMethod(operationName = "CambiaEstatusFactura33", action = "http://tempuri.org/CambiaEstatusFactura33")
    @WebResult(name = "CambiaEstatusFactura33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CambiaEstatusFactura33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CambiaEstatusFactura33")
    @ResponseWrapper(localName = "CambiaEstatusFactura33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CambiaEstatusFactura33Response")
    public CambiaEstatus33Response cambiaEstatusFactura33(
        @WebParam(name = "cambiorequest", targetNamespace = "http://tempuri.org/")
        CambiaEstatus33Request cambiorequest);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VersionWS20180603_00", action = "http://tempuri.org/VersionWS20180603_00")
    @WebResult(name = "VersionWS20180603_00Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VersionWS20180603_00", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VersionWS2018060300")
    @ResponseWrapper(localName = "VersionWS20180603_00Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VersionWS2018060300Response")
    public String versionWS2018060300();

    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.EFResponse
     */
    @WebMethod(operationName = "GeneraTimbradoEF", action = "http://tempuri.org/GeneraTimbradoEF")
    @WebResult(name = "GeneraTimbradoEFResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraTimbradoEF", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraTimbradoEF")
    @ResponseWrapper(localName = "GeneraTimbradoEFResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraTimbradoEFResponse")
    public EFResponse generaTimbradoEF(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        EFRequest request);

    /**
     * 
     * @param asigna
     * @return
     *     returns org.tempuri.ClienteResponse
     */
    @WebMethod(operationName = "AsignacionFolios", action = "http://tempuri.org/AsignacionFolios")
    @WebResult(name = "AsignacionFoliosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AsignacionFolios", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AsignacionFolios")
    @ResponseWrapper(localName = "AsignacionFoliosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AsignacionFoliosResponse")
    public ClienteResponse asignacionFolios(
        @WebParam(name = "Asigna", targetNamespace = "http://tempuri.org/")
        AsignaFolios2 asigna);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.TimbradoPlusComercioExteriorResponse
     */
    @WebMethod(operationName = "TimbraCFDIComercioExteriorplus11", action = "http://tempuri.org/TimbraCFDIComercioExteriorplus11")
    @WebResult(name = "TimbraCFDIComercioExteriorplus11Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIComercioExteriorplus11", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIComercioExteriorplus11")
    @ResponseWrapper(localName = "TimbraCFDIComercioExteriorplus11Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIComercioExteriorplus11Response")
    public TimbradoPlusComercioExteriorResponse timbraCFDIComercioExteriorplus11(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        TimbradoPlusComercioExteriorRequest comerciorequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaResponse33
     */
    @WebMethod(operationName = "TimbraCFDINominaPlus12V33", action = "http://tempuri.org/TimbraCFDINominaPlus12V33")
    @WebResult(name = "TimbraCFDINominaPlus12V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDINominaPlus12V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12V33")
    @ResponseWrapper(localName = "TimbraCFDINominaPlus12V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12V33Response")
    public TimbradoPlusNominaResponse33 timbraCFDINominaPlus12V33(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        TimbradoPlusNominaRequest33 nominarequest);

    /**
     * 
     */
    @WebMethod(operationName = "GeneraSpeiOpenPay", action = "http://tempuri.org/GeneraSpeiOpenPay")
    @RequestWrapper(localName = "GeneraSpeiOpenPay", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraSpeiOpenPay")
    @ResponseWrapper(localName = "GeneraSpeiOpenPayResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraSpeiOpenPayResponse")
    public void generaSpeiOpenPay();

    /**
     * 
     */
    @WebMethod(operationName = "TiendaOpenPay", action = "http://tempuri.org/TiendaOpenPay")
    @RequestWrapper(localName = "TiendaOpenPay", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TiendaOpenPay")
    @ResponseWrapper(localName = "TiendaOpenPayResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TiendaOpenPayResponse")
    public void tiendaOpenPay();

    /**
     * 
     * @param timbraRequest
     * @return
     *     returns org.tempuri.TimbraCFDI33Response
     */
    @WebMethod(operationName = "TimbraCFDIV33", action = "http://tempuri.org/TimbraCFDIV33")
    @WebResult(name = "TimbraCFDIV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV33")
    @ResponseWrapper(localName = "TimbraCFDIV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIV33Response")
    public TimbraCFDI33Response timbraCFDIV33(
        @WebParam(name = "timbraRequest", targetNamespace = "http://tempuri.org/")
        TimbraCFDI33Request timbraRequest);

    /**
     * 
     * @param timbraRequest
     * @return
     *     returns org.tempuri.TimbraCFDI33Response
     */
    @WebMethod(operationName = "TimbraCFDIB64", action = "http://tempuri.org/TimbraCFDIB64")
    @WebResult(name = "TimbraCFDIB64Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIB64", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIB64")
    @ResponseWrapper(localName = "TimbraCFDIB64Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIB64Response")
    public TimbraCFDI33Response timbraCFDIB64(
        @WebParam(name = "timbraRequest", targetNamespace = "http://tempuri.org/")
        TimbraCFDI33Request timbraRequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaCancelacionResponse
     */
    @WebMethod(operationName = "CancelaCFDINominaPlus12", action = "http://tempuri.org/CancelaCFDINominaPlus12")
    @WebResult(name = "CancelaCFDINominaPlus12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDINominaPlus12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINominaPlus12")
    @ResponseWrapper(localName = "CancelaCFDINominaPlus12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINominaPlus12Response")
    public TimbradoPlusNominaCancelacionResponse cancelaCFDINominaPlus12(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        TimbradoPlusNominaCancelacioRequest cancelacionrequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.CFDINominaResponse
     */
    @WebMethod(operationName = "GeneraCFDINomina12", action = "http://tempuri.org/GeneraCFDINomina12")
    @WebResult(name = "GeneraCFDINomina12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDINomina12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12")
    @ResponseWrapper(localName = "GeneraCFDINomina12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12Response")
    public CFDINominaResponse generaCFDINomina12(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        CFDINominaRequest nominarequest);

    /**
     * 
     * @param cancelacionrequest
     * @return
     *     returns org.tempuri.CFDINominaCancelacionResponse
     */
    @WebMethod(operationName = "CancelaCFDINomina12", action = "http://tempuri.org/CancelaCFDINomina12")
    @WebResult(name = "CancelaCFDINomina12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaCFDINomina12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINomina12")
    @ResponseWrapper(localName = "CancelaCFDINomina12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelaCFDINomina12Response")
    public CFDINominaCancelacionResponse cancelaCFDINomina12(
        @WebParam(name = "cancelacionrequest", targetNamespace = "http://tempuri.org/")
        CFDICancelacionNominaRequest cancelacionrequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponseComplementoDePagos
     */
    @WebMethod(operationName = "GeneraCFDIV33CPagos", action = "http://tempuri.org/GeneraCFDIV33CPagos")
    @WebResult(name = "GeneraCFDIV33CPagosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33CPagos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33CPagos")
    @ResponseWrapper(localName = "GeneraCFDIV33CPagosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33CPagosResponse")
    public CFDIResponseComplementoDePagos generaCFDIV33CPagos(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequestComplementoDePago cfdiRequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIV33SiVale", action = "http://tempuri.org/GeneraCFDIV33SiVale")
    @WebResult(name = "GeneraCFDIV33SiValeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33SiVale", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33SiVale")
    @ResponseWrapper(localName = "GeneraCFDIV33SiValeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33SiValeResponse")
    public CFDIResponse generaCFDIV33SiVale(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequestSiVale cfdiRequest);

    /**
     * 
     * @param comerciorequest
     * @return
     *     returns org.tempuri.CFDIComercioExteriorResponse
     */
    @WebMethod(operationName = "GeneraCFDIComerioExterior11", action = "http://tempuri.org/GeneraCFDIComerioExterior11")
    @WebResult(name = "GeneraCFDIComerioExterior11Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIComerioExterior11", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11")
    @ResponseWrapper(localName = "GeneraCFDIComerioExterior11Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIComerioExterior11Response")
    public CFDIComercioExteriorResponse generaCFDIComerioExterior11(
        @WebParam(name = "comerciorequest", targetNamespace = "http://tempuri.org/")
        CFDIComercioExteriorRequest comerciorequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIV33Plus", action = "http://tempuri.org/GeneraCFDIV33Plus")
    @WebResult(name = "GeneraCFDIV33PlusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33Plus", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33Plus")
    @ResponseWrapper(localName = "GeneraCFDIV33PlusResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33PlusResponse")
    public CFDIResponse generaCFDIV33Plus(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest cfdiRequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDITimbradoPlusReponse
     */
    @WebMethod(operationName = "TimbraCFDIPlusV33", action = "http://tempuri.org/TimbraCFDIPlusV33")
    @WebResult(name = "TimbraCFDIPlusV33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDIPlusV33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIPlusV33")
    @ResponseWrapper(localName = "TimbraCFDIPlusV33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDIPlusV33Response")
    public CFDITimbradoPlusReponse timbraCFDIPlusV33(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDITimbradoPlusRequest cfdiRequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDITimbradoPlusReponseComplementoDePagos
     */
    @WebMethod(operationName = "GeneraCFDPlusV33ComplementoDePagos", action = "http://tempuri.org/GeneraCFDPlusV33ComplementoDePagos")
    @WebResult(name = "GeneraCFDPlusV33ComplementoDePagosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDPlusV33ComplementoDePagos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDPlusV33ComplementoDePagos")
    @ResponseWrapper(localName = "GeneraCFDPlusV33ComplementoDePagosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDPlusV33ComplementoDePagosResponse")
    public CFDITimbradoPlusReponseComplementoDePagos generaCFDPlusV33ComplementoDePagos(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDITimbradoPlusRequestComplementoDePagos cfdiRequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.TimbradoPlusNominaResponse
     */
    @WebMethod(operationName = "TimbraCFDINominaPlus12", action = "http://tempuri.org/TimbraCFDINominaPlus12")
    @WebResult(name = "TimbraCFDINominaPlus12Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TimbraCFDINominaPlus12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12")
    @ResponseWrapper(localName = "TimbraCFDINominaPlus12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TimbraCFDINominaPlus12Response")
    public TimbradoPlusNominaResponse timbraCFDINominaPlus12(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        TimbradoPlusNominaRequest nominarequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIV33Consultores", action = "http://tempuri.org/GeneraCFDIV33Consultores")
    @WebResult(name = "GeneraCFDIV33ConsultoresResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33Consultores", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33Consultores")
    @ResponseWrapper(localName = "GeneraCFDIV33ConsultoresResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33ConsultoresResponse")
    public CFDIResponse generaCFDIV33Consultores(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest cfdiRequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.CFDINominaResponse33
     */
    @WebMethod(operationName = "GeneraCFDINomina12V33Masiva", action = "http://tempuri.org/GeneraCFDINomina12V33Masiva")
    @WebResult(name = "GeneraCFDINomina12V33MasivaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDINomina12V33Masiva", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12V33Masiva")
    @ResponseWrapper(localName = "GeneraCFDINomina12V33MasivaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12V33MasivaResponse")
    public CFDINominaResponse33 generaCFDINomina12V33Masiva(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        CFDINominaRequest33Masiva nominarequest);

    /**
     * 
     * @param cfdiRequest
     * @return
     *     returns org.tempuri.CFDIResponse
     */
    @WebMethod(operationName = "GeneraCFDIV33Global", action = "http://tempuri.org/GeneraCFDIV33Global")
    @WebResult(name = "GeneraCFDIV33GlobalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDIV33Global", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33Global")
    @ResponseWrapper(localName = "GeneraCFDIV33GlobalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDIV33GlobalResponse")
    public CFDIResponse generaCFDIV33Global(
        @WebParam(name = "CFDIRequest", targetNamespace = "http://tempuri.org/")
        CFDIRequest cfdiRequest);

    /**
     * 
     * @param nominarequest
     * @return
     *     returns org.tempuri.CFDINominaResponse33
     */
    @WebMethod(operationName = "GeneraCFDINomina12V33", action = "http://tempuri.org/GeneraCFDINomina12V33")
    @WebResult(name = "GeneraCFDINomina12V33Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCFDINomina12V33", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12V33")
    @ResponseWrapper(localName = "GeneraCFDINomina12V33Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GeneraCFDINomina12V33Response")
    public CFDINominaResponse33 generaCFDINomina12V33(
        @WebParam(name = "nominarequest", targetNamespace = "http://tempuri.org/")
        CFDINominaRequest33 nominarequest);

    /**
     * 
     * @param consulta
     * @return
     *     returns org.tempuri.ConsultaFolioFiscalResponse2
     */
    @WebMethod(operationName = "ConsultaFolioFiscal", action = "http://tempuri.org/ConsultaFolioFiscal")
    @WebResult(name = "ConsultaFolioFiscalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaFolioFiscal", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaFolioFiscal")
    @ResponseWrapper(localName = "ConsultaFolioFiscalResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaFolioFiscalResponse")
    public ConsultaFolioFiscalResponse2 consultaFolioFiscal(
        @WebParam(name = "Consulta", targetNamespace = "http://tempuri.org/")
        ConsultaFolioFiscalRequest consulta);

}
